### ISSUE TITLE
CNF的Var 與Abc_Obj_t 的 ID之間的關聯

### ISSUE THREAD

**Issue by david057178-2020** [NTU-ALComLab/LSV-PA#215]
助教您好

以下是我目前的理解不知道有沒有誤:

在Abc_Ntk_t中，每個Abc_Obj_t都有自己的ID以及name
以1-bit adder為例，三個input的(ID, NAME)分別是(1,a)(2,b)(3,c-in)
當我把Abc_Ntk_t變成Aig，並進一步變成Cnf_Dat_t時
其Var與ID之間的mapping應該是記錄在Cnf_Dat_t->pVarNums中
其中pVarNums的index代表原先的ID，其值代表他所對應的Var
以1-bit adder為例，Cnf_Dat_t->pVarNums[1] = 3，表示第一個input (1,a) 對應到的var是3(從3開始應該是與var創建的順序有關)

我的問題是:
1.從Abc_Obj_t ID到Var可以直接查pVarNum，但似乎卻沒辦法很快的反向搜索?
當我拿到一個var想知道他對應到的Abc_Obj_t ID，這個mapping我們是不是要自己實作?
Wiki Key Questions的第三點說要rename variable指的是這件事嗎?(創建一個array去紀錄Var to ID 的mapping之類的)

2.在1-bit adder中，Cnf_Dat_t->pVarNums[0] = 6。
如果我上述的理解沒有錯的話，表示var 6代表的是Abc_Obj_t的constant node(ID = 0)
然而我把1-bit adder 的c-out的cnf印出來長這樣

full_adder_c-out
2 3 5 
2 4 5 
2 3 4 
-2 -3 -4 
-2 -4 -5 
-2 -3 -5 
6 
1 2 
-1 -2 

其中var[3,4,5]分別對應到input[a, b, c-in]
那var 1、 2是什麼呢?(在pVarNums沒有紀錄)
還有var 6如果是constant node的話
我看不太懂為什麼1-bit adder 的c-out的cnf是長這樣

謝謝助教解惑

**Comment by david057178-2020** [comment]
針對問題2，我知道CNF為甚麼長那樣了，也知道pVarNums的功用。
現在的問題是Wiki Key Questions的第三點所提示的rename的部分，在這次的實作中我們應該會陸續建造許多constrain，也就是造出許多新的var，然而要知道每個var number分別對應的是什麼變數，是否有什麼有效率的方式去記錄呢?
我目前想到的是建造一個mapping table，把流水編號的var number map到我們自定義的變數名稱，但感覺Wiki所說的rename應該是在提示有更好的方式，希望能針對這點獲得更進一步的提示

謝謝助教

**Comment by nianzelee** [comment]
> 當我把Abc_Ntk_t變成Aig，並進一步變成Cnf_Dat_t時
> 其Var與ID之間的mapping應該是記錄在Cnf_Dat_t->pVarNums中
> 其中pVarNums的index代表原先的ID，其值代表他所對應的Var

Correct. Please note that `pVarNums` maps an ID of **`Aig_Obj_t`** to its variable.
In the context of PA2, the IDs of `Abc_Obj_t` happen to be the same as those of `Aig_Obj_t` because the input circuit is in AIGER format, but this does not hold in general.

> 1.從Abc_Obj_t ID到Var可以直接查pVarNum，但似乎卻沒辦法很快的反向搜索?
> 當我拿到一個var想知道他對應到的Abc_Obj_t ID，這個mapping我們是不是要自己實作?

AFAIK there is no such mapping in ABC. You have to implement it if it is necessary in your solution.
I wonder why it is necessary though. In the reference program, I did not need this mapping.

> Wiki Key Questions的第三點說要rename variable指的是這件事嗎?(創建一個array去紀錄Var to ID 的mapping之類的)

No. It refers to creating a fresh copy of the formula. As mentioned in the lecture, we need two copies of the formula, one for the positive cofactor and the other for the negative cofactor.


> 2.在1-bit adder中，Cnf_Dat_t->pVarNums[0] = 6。
> 如果我上述的理解沒有錯的話，表示var 6代表的是Abc_Obj_t的constant node(ID = 0)
> 然而我把1-bit adder 的c-out的cnf印出來長這樣
> 
> full_adder_c-out
> 2 3 5
> 2 4 5
> 2 3 4
> -2 -3 -4
> -2 -4 -5
> -2 -3 -5
> 6
> 1 2
> -1 -2
> 
> 其中var[3,4,5]分別對應到input[a, b, c-in]
> 那var 1、 2是什麼呢?(在pVarNums沒有紀錄)
> 還有var 6如果是constant node的話
> 我看不太懂為什麼1-bit adder 的c-out的cnf是長這樣

Your CNF looks strange. How did you print this CNF?
The following is printed by method `Cnf_DataPrint()`:

```
p cnf 9 19
3 -5 6 -7 
3 -5 -6 7 
3 5 -6 -7 
3 5 6 7 
-3 -5 6 7 
-3 -5 -6 -7 
-3 5 -6 7 
-3 5 6 -7 
4 5 7 
4 6 7 
4 5 6 
-4 -5 -6 
-4 -6 -7 
-4 -5 -7 
8 
1 3 
-1 -3 
2 4 
-2 -4
```

The primary inputs `a`, `b`, and `c-in` map to variables `5`, `6`, and `7`.
The primary outputs `sum` and `c-out` map to variables `1` and `2`.

**Comment by nianzelee** [comment]
> 現在的問題是Wiki Key Questions的第三點所提示的rename的部分，在這次的實作中我們應該會陸續建造許多constrain，也就是造出許多新的var，然而要知道每個var number分別對應的是什麼變數，是否有什麼有效率的方式去記錄呢?

Sorry but I could not understand this question. A variable is just an integer. It does not map to another variable.

> 我目前想到的是建造一個mapping table，把流水編號的var number map到我們自定義的變數名稱，但感覺Wiki所說的rename應該是在提示有更好的方式，希望能針對這點獲得更進一步的提示

In addition to variables involved in formulas derived from method`Cnf_Derive()`, I only created controlling variables for each primary input. I stored these variables by an array, similar to `pVarNums`.
