### ISSUE TITLE
What is four-number serial adder?

### ISSUE THREAD

**Issue by mirkat1206** [NTU-ALComLab/LSV-PA#323]
I am confused about "four-number serial adder".

Can TA give a more specific definition about it? 
i.e. Can TA  be more specific on inputs/outputs relation, perhaps give us some example?

**Comment by Luo-Yun-Rong** [comment]
<img width="697" alt="2number_serial_adder" src="https://user-images.githubusercontent.com/31838753/135738794-3a4b01f3-8af4-47cb-9865-6b8e0fff477d.png">

The figure is a 2-number serial adder, with 1-bit inputs `a,b`, 1-bit output `s`, and a latch with 1-bit input `cout` and 1-bit output `cin`.  For a 4-number serial adder, your BLIF should contain input list:  1-bit inputs `a,b,c,d`, and output list: 1-bit output `s`. However,  you may have more than one latch, since you may have more carry bits.

**Comment by mirkat1206** [comment]
got it. Thanks a lot.
