### ISSUE TITLE
"show" Command Doesn't Work Well on Mac with XQuartz(gv)

### ISSUE THREAD

**Issue by asfhiolNick** [NTU-ALComLab/LSV-PA#537]
I'm working on a MacBook Pro. According to this advice, XQuartz(gv) should be used instead of GSView on a Mac.
<img width="906" alt="截圖 2023-09-12 下午3 11 03" src="https://github.com/NTU-ALComLab/LSV-PA/assets/59384814/c9cc25d6-2791-4294-a4c7-999fd248e8b3">

However, when I run the "show" command in the abc program, I get the following warning messages:
<img width="567" alt="截圖 2023-09-12 下午3 30 32" src="https://github.com/NTU-ALComLab/LSV-PA/assets/59384814/4d909ce2-accc-4acf-a266-93db0b979403">

If I first set export LANG=C and then run the "show" command in the abc program, an XQuartz(gv) window pops up but it's empty.
<img width="1158" alt="截圖 2023-09-12 下午3 06 27" src="https://github.com/NTU-ALComLab/LSV-PA/assets/59384814/8ee57e10-3560-4276-b3e9-7d5f79bad227">

How can I fix it? Thanks a lot.

Reference:
advice from 
http://geodesy.gl.ntu.edu.tw/index.files/%E6%95%99%E5%AD%B8%E8%B3%87%E6%BA%90/%E5%9C%B0%E7%90%83%E7%89%A9%E7%90%86%E8%B3%87%E6%96%99%E8%99%95%E7%90%86%20(GMT)/Powerpoint_install_Introduction/gmt600_2020_install.pdf

**Comment by ghdftff542** [comment]
Sorry that I cannot access a Mac environment, so I cannot reproduce your results. 
However, when I use the "show" command, I also receive the message "Warning: Missing charsets in String to FontSet conversion," but my graph displays correctly.
Therefore, I guess this message might not be the root cause of the issue.

By the way, is the .ps file successfully generated? 
If so, an alternative approach could be to use an online viewer such as https://ehubsoft.herokuapp.com/psviewer/.

**Comment by asfhiolNick** [comment]
Thank you so much. 
Even though XQuartz(gv) still doesn't work, a .ps file is generated and can be viewed online.

**Comment by angtsusiong** [comment]
> I'm working on a MacBook Pro. According to this advice, XQuartz(gv) should be used instead of GSView on a Mac.

This is a misunderstanding about the advice.
GSView is gv, and XQuartz is a dependency for running an X app on OS X. GSView is an X app thus your system needs the ability to handle X11, which may not be supported by default.

**Comment by angtsusiong** [comment]
The second warning message "Warning: Unable to load any usable fontset" is fatal for gv. This causes gv crash and nothing shows up.
After setting the environment variable, you have to make sure you have misc/xxxdpi fonts and the order of them came before any OTF/TTF fonts in X.
Since I don't have an OS X environment, I don't know the path of those fonts and the installation method of them. Good luck.
