### ISSUE TITLE
problem2 (b)

### ISSUE THREAD

**Issue by david057178-2020** [NTU-ALComLab/LSV-PA#74]
助教您好

第二題的(b)就我目前的理解是，在strash之後ABC會將network存成structurally hashed AIG的形式。此時如果要恢復成SOP，應該只需要下"logic"這個指令即可。因此不懂為何題目敘述是要我們列出 a sequence of command(我的理解只需要"logic"這一個command)。

我自己推測的幾個可能是:
1. 題目要求從讀進aig檔開始
因此是read file.aig -> logic ->done!
2.題目要求不只是要SOP，而是要在被strash化簡之前的function node的SOP
關於這點我有查到一個指令是"renode"，根據ABC官網的說法它可以recreating SOP logic network from the AIG 。
但是我拿4-bit_Adder實驗的結果發現，strash之後再renode並不能完全恢復成strash前的模樣。
而且如果不斷的重複strash->renode->strash->renode->strash-> ...，每次出來的結果也不一樣。
因此不知道該如何理解renode這個指令。

謝謝解惑

**Comment by nianzelee** [comment]
> 因此不懂為何題目敘述是要我們列出 a sequence of command(我的理解只需要"logic"這一個command)。

A single command can also be seen as *a sequence of commands* with the length of the sequence equals one.

>    但是我拿4-bit_Adder實驗的結果發現，strash之後再renode並不能完全恢復成strash前的模樣。

Command `renode` does not guarantee to restore a structurally hashed circuit back to its original topology.
It only simplifies a logic network heuristically. Note that you are **not** required to restore the network structure.

**Comment by nthucat** [comment]
助教您好：
       想確認一下我們欲轉回SOP的structurally hashed AIG應該是要用指令生成，而不是直接讀一個AIG檔對嗎？此外我用renode想要把一個structurally hashed AIG轉回SOP，但是看stats時沒看到cube的個數，只有AIG的個數，show出來的圖看起來也是個AIG，請問這樣是不是沒有成功轉回SOP呢？麻煩助教解惑，感謝您!
![image](https://user-images.githubusercontent.com/58925841/95702212-4819e000-0c7e-11eb-9df3-49651f76f942.png)

**Comment by nianzelee** [comment]
> 想確認一下我們欲轉回SOP的structurally hashed AIG應該是要用指令生成，而不是直接讀一個AIG檔對嗎？

It does not matter. You can assume the input circuit to be an AIG circuit.

> 此外我用renode想要把一個structurally hashed AIG轉回SOP，但是看stats時沒看到cube的個數

Notice the difference between the outcomes printed by `abc 03> print_stats` and `abc 04> print_stats`.
The former one displays `and = 44` because the circuit is an AIG.
The latter one displays `nd = 24` because the circuit is a logic network.
No `cube` is displayed because the functions of internal nodes are represented by AIG cirucits but not by SOPs.

> 但是打logic指令它卻說這已經不是個structurally hashed AIG結構了

As explained above, the circuit becomes a logic circuit with functions of internal nodes represented in AIG.
The circuit is no longer an AIG circuit.
